<template>
    <button
        class="
            tw-bg-red-600
            active:tw-bg-red-700
            dark:focus:tw-ring-offset-slate-800
            focus:tw-outline-none
            focus:tw-ring-2
            focus:tw-ring-offset-2
            focus:tw-ring-red-500
            hover:tw-bg-red-500
            tw-border
            tw-border-transparent
            tw-duration-300
            tw-ease-in-out
            tw-font-semibold
            tw-inline-flex
            tw-items-center
            tw-px-4
            tw-py-2
            tw-rounded-md
            tw-text-slate-50
            tw-text-xs
            tw-tracking-widest
            tw-transition
            tw-uppercase
            "
    >
        <slot />
    </button>
</template>
