<template>
    <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        class="
            tw-duration-300
            dark:tw-stroke-slate-50
            dark:tw-text-slate-50
            tw-ease-in-out
            tw-font-bold
            tw-select-none
            tw-stroke-slate-900
            tw-text-2xl
            tw-text-slate-900
            "
    >
        <text
            x="3"
            y="21.5"
            font-family="Roboto"
            font-size="27"
            fill="currentColor"
        >
            Z
        </text>
    </svg>
</template>
